[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  force = true
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
